### ISSUE TITLE
Mod download/ Loading

### ISSUE THREAD

**Issue by Bluetear93** [TeamAOF/All-of-Fabric-4#1]
Having issues trying to install the server, any help will be appreciated. Thanks.

[20:25:06] [main/INFO]: Loading for game Minecraft 1.17
[20:25:06] [ForkJoinPool-1-worker-13/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[20:25:06] [ForkJoinPool-1-worker-4/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[20:25:07] [ForkJoinPool-1-worker-1/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[20:25:07] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: mo_glass requires {java @ [>=16]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177) ~[fabric-server-launch.jar:?]
	... 12 more

**Server side:**

[20:26:17] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
[20:26:17] [INFO]    Minecraft ServerStarter install/launcher jar
[20:26:17] [INFO]    (Created by BloodWorkXGaming with the help of "Team RAM")
[20:26:17] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
[20:26:17] [INFO]
[20:26:17] [INFO]    This jar will launch a Minecraft Forge/Fabric Modded server
[20:26:17] [INFO]
[20:26:17] [INFO]    Github:    https://github.com/BloodyMods/ServerStarter
[20:26:17] [INFO]    Discord:   https://discord.gg/A3c5YfV
[20:26:17] [INFO]
[20:26:17] [INFO] You are playing All of Fabric 4
[20:26:17] [INFO] Starting to install/launch the server, lean back!
[20:26:17] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
[20:26:17] [INFO]
[20:26:17] [INFO] Pinging 8.8.8.8.
[20:26:17] [INFO] Reached 8.8.8.8: true
[20:26:17] [INFO] Pinging 1.0.0.1.
[20:26:17] [INFO] Reached 1.0.0.1: true
[20:26:17] [INFO] Reached 2 out of 2 IPs.
[20:26:17] [INFO] Server is already installed to correct version, to force install delete the serverstarter.lock File.
[20:26:17] [INFO] Starting Loader, output incoming
[20:26:18] [main/INFO]: Loading for game Minecraft 1.17
[20:26:19] [ForkJoinPool-1-worker-1/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[20:26:19] [ForkJoinPool-1-worker-13/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[20:26:19] [ForkJoinPool-1-worker-10/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[20:26:19] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: mo_glass requires {java @ [>=16]}
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177) ~[fabric-server-launch.jar:?]
        ... 12 more

**Comment by dandin87** [comment]
You need to add download and install java 16 and set the instance to use Java 16, curseforge launcher will use the new java 16 built into the vanilla launcher but GD Launcher and I believe MultiMC you have to manually set the instance to use java 16
