### ISSUE TITLE
Mo Glass dependency; How do I resolve this?

### ISSUE THREAD

**Issue by typw11** [TeamAOF/All-of-Fabric-4#112]
I have used the serverpack to install the mods in my archlinux system,
It also having the same issue in my windows system.

Here is the logs
```
Starting Loader, output incoming
[11:34:35] [main/INFO]: Loading for game Minecraft 1.17.1
[11:34:36] [ForkJoinPool-1-worker-1/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[11:34:36] [ForkJoinPool-1-worker-1/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[11:34:37] [ForkJoinPool-1-worker-1/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[11:34:37] [ForkJoinPool-1-worker-1/WARN]: The mod "qcommon-croco" contains invalid entries in its mod json:
- Unsupported root entry "links" at line 10 column 10
[11:34:37] [ForkJoinPool-1-worker-1/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[11:34:37] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: mo_glass requires {java @ [>=16]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-server-launch.jar:?]
	... 12 more
[11:34:37] [INFO] Server has been stopped, it has started 2 times in 60min
[11:34:37] [INFO] Restarting server in 10 seconds, press ctrl+c to stop

```

**Comment by css-01** [comment]
Hello,

The problem is due to an old version of java that you have installed on the server side. Minecraft 1.17 requires java 16 instead of 8 that you have. The problem will be solved if you update the software. If you do not have access to the server via ssh client, please contact your service provider, usually they make the change without any problems.
