### ISSUE TITLE
Pillagers Crashing The Game

### ISSUE THREAD

**Issue by WarriorsMind** [TeamAOF/All-of-Fabric-4#13]
After the 0.0.4 update, when ever you hit or get too close to a pillager the game/server crashes. So far the only option i add was to disable the raids and patrols.

Heres the error it gives 

Description: Ticking entity
java.lang.ClassCastException: class net.minecraft.class_1604 cannot be cast to class net.minecraft.class_1657 (net.minecraft.class_1604 and net.minecraft.class_1657 are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @121314f7)
at net.minecraft.class_1764.method_7765(class_1764.java:541)
	at net.minecraft.class_1764.method_7767(class_1764.java:131)
	at net.minecraft.class_1764.method_7840(class_1764.java:106)
	at net.minecraft.class_1799.method_7930(class_1799.java:540)
	at net.minecraft.class_1309.method_6075(class_1309.java:3093)
	at net.minecraft.class_1383.method_6268(class_1383.java:125)
	at net.minecraft.class_4135.method_6268(class_4135.java:55)
	at net.minecraft.class_1355.tickGoals(class_1355.java:657)
	at net.minecraft.class_1355.method_6275(class_1355.java:556)
	at net.minecraft.class_1308.method_6023(class_1308.java:732)
	at net.minecraft.class_1309.method_6007(class_1309.java:2597)
	at net.minecraft.class_1308.method_6007(class_1308.java:538)
	at net.minecraft.class_1588.method_6007(class_1588.java:43)
	at net.minecraft.class_3763.method_6007(class_3763.java:114)
	at net.minecraft.class_1309.method_5773(class_1309.java:2342)
	at net.minecraft.class_1308.method_5773(class_1308.java:338)
	at net.minecraft.class_3218.method_18762(class_3218.java:656)
	at net.minecraft.class_1937.method_18472(class_1937.java:483)
	at net.minecraft.class_3218.method_31420(class_3218.java:418)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:393)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
	at net.minecraft.class_3176.method_3813(class_3176.java:334)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:692)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by ImAK9** [comment]
Try updating to fabric loader 0.11.6 and let me know if problem is solved.

**Comment by WarriorsMind** [comment]
I can't seem to update it to 0.11.6. I tried using the fabric instaler on both server and the pack and even replace the ,fabric and version folder with the one in my .minecraft folder that is 0.11.6 and it still use the 0.11.3

**Comment by WarriorsMind** [comment]
I was able to update the pack to 0.11.6 but how do you update a server ?

**Comment by dandin87** [comment]
Update nyfs quivers, it will fix the issue.
https://www.curseforge.com/minecraft/mc-mods/nyfs-quivers/files/3368073

**Comment by dandin87** [comment]
> I was able to update the pack to 0.11.6 but how do you update a server ?
> 
> Update: Even updating to 0.11.6 still cause to crash when next to pillager and piglings . I have try in singleplay by porting over my server world and still crashes
> 
> Update2: I tried a new singleplayer. Nothing around. A brand new world and still crashes when pillage are near.

As for updating a server loader version, you would need to replace the .fabric and .mixin.out folders, and the fabric-server-launch.jar file. The name of this file could be changed on a Hosting Site, and could be in a /jar folder. Check fabric-server-launcher.properties if the file's name or location has changed.

**Comment by WarriorsMind** [comment]
> 
> 
> Update nyfs quivers, it will fix the issue.
> https://www.curseforge.com/minecraft/mc-mods/nyfs-quivers/files/3368073

It seem to have fix the problem without the need to update the fabric loader. Thanks alot
