### ISSUE TITLE
Critical error while trying to start a server

### ISSUE THREAD

**Issue by MishaczeQ** [TeamAOF/All-of-Fabric-4#6]
Trying to set up a server for the modpack but after agreeing to the EULA server keeps crashing

here is a log from the terminal:
`./startserver.sh
Skipping download. Using existing serverstarter-2.0.1.jar
[17:43:22] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
[17:43:22] [INFO]    Minecraft ServerStarter install/launcher jar
[17:43:22] [INFO]    (Created by BloodWorkXGaming with the help of "Team RAM")
[17:43:22] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
[17:43:22] [INFO] 
[17:43:22] [INFO]    This jar will launch a Minecraft Forge/Fabric Modded server
[17:43:22] [INFO] 
[17:43:22] [INFO]    Github:    https://github.com/BloodyMods/ServerStarter
[17:43:22] [INFO]    Discord:   https://discord.gg/A3c5YfV
[17:43:22] [INFO] 
[17:43:22] [INFO] You are playing All of Fabric 4
[17:43:22] [INFO] Starting to install/launch the server, lean back!
[17:43:22] [INFO] :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
[17:43:22] [INFO] 
[17:43:22] [INFO] Pinging 8.8.8.8.
[17:43:23] [INFO] Reached 8.8.8.8: false
[17:43:23] [INFO] Pinging 1.0.0.1.
[17:43:24] [INFO] Reached 1.0.0.1: false
[17:43:24] [INFO] Reached 0 out of 2 IPs.
[17:43:24] [ERROR] Not every host could be reached. There could be a problem with your internet connection!!!!
[17:43:24] [INFO] Server is already installed to correct version, to force install delete the serverstarter.lock File.
[17:43:24] [INFO] Starting Loader, output incoming
[17:43:25] [main/INFO]: Loading for game Minecraft 1.17
[17:43:26] [ForkJoinPool-1-worker-2/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[17:43:26] [ForkJoinPool-1-worker-2/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[17:43:26] [ForkJoinPool-1-worker-3/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[17:43:26] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: mo_glass requires {java @ [>=16]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_292]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_292]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177) ~[fabric-server-launch.jar:?]
	... 12 more
[17:43:26] [INFO] Server has been stopped, it has started 1 times in 60min
[17:43:26] [INFO] Restarting server in 10 seconds, press ctrl+c to stop
`

**Comment by dandin87** [comment]
In server-setupconfig.yaml you need to set the path to your Java 16 install. If you have not installed Java 16 outside of using it with Curseforge Launcher and Minecrafts builtin Java16 for 1.17, then downlaod it from here. https://adoptopenjdk.net/?variant=openjdk16&jvmVariant=hotspot
Here is the setting you need to change. This is assuming the using the adoptOpenJDK java 16.
  # In case you have multiple javas installed you can add a absolute path to it here
  # if the value is "", null, or ~ then 'java' from PATH is going to be used
  # Example: "\"C:/Program Files/Java/jre1.8.0_201/bin/java.exe\""
  forcedJavaPath: "\"C:/Program Files/AdoptOpenJDK/jdk-16.0.1.9-hotspot/bin/java.exe\""
