### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by Iwan444** [TeamAOF/All-of-Fabric-4#76]
[16:15:33] [main/INFO]: Loading for game Minecraft 1.17.1
[16:15:33] [ForkJoinPool-1-worker-9/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[16:15:33] [ForkJoinPool-1-worker-6/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[16:15:33] [ForkJoinPool-1-worker-10/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[16:15:33] [ForkJoinPool-1-worker-3/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[16:15:33] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: mo_glass requires {java @ [>=16]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-server-launch.jar:?]
	... 12 more

**Comment by AbyssalCode** [comment]
[12:43:25] [main/INFO]: Loading for game Minecraft 1.17.1
[12:43:25] [ForkJoinPool-1-worker-17/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[12:43:25] [ForkJoinPool-1-worker-23/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[12:43:26] [ForkJoinPool-1-worker-23/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[12:43:26] [ForkJoinPool-1-worker-19/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[12:43:26] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.3.0+a02b44633d, also found 0.3.0+a02b446318, 0.3.0+c88702897d
 - Conflicting versions found for fabric-key-binding-api-v1: used 1.0.4+a02b446318, also found 1.0.4+a02b44633d
 - Conflicting versions found for fabric-lifecycle-events-v1: used 1.4.4+a02b44633d, also found 1.4.4+a02b446318
 - Conflicting versions found for fabric-tag-extensions-v0: used 1.1.4+a02b44633d, also found 1.1.4+a02b446318
 - Mod 'Beenfo' (beenfo) recommends version 1.1.7 or later of mod modupdater, which is missing!
	 - You must install version 1.1.7 or later of modupdater.
 - Conflicting versions found for fabric-tool-attribute-api-v1: used 1.2.12+b7ab61213d, also found 1.2.12+b7ab612118
 - Conflicting versions found for fabric-events-interaction-v0: used 0.4.9+a722d8c018, also found 0.4.9+a722d8c03d
 - Conflicting versions found for fabric-screen-api-v1: used 1.0.4+155f865c18, also found 1.0.4+198a96213d
 - Conflicting versions found for fabric-item-api-v1: used 1.2.4+a02b44633d, also found 1.2.4+a02b446318
 - Mod 'BetterF3' (betterf3) recommends version 2.0.0.* of mod 'Mod Menu' (modmenu), but a non-matching version is present: 2.0.2!
	 - You must install version 2.0.0.* of 'Mod Menu' (modmenu).
	 - Mod 'Mod Menu' (modmenu) v2.0.2 is being provided by 'Vanilla Hammers' (vanilla-hammers) v2.0.2.
[12:43:26] [main/INFO]: [FabricLoader] Loading 306 mods:
	- addendum@1.0.2
	- adorn@2.1.3+1.17.1
	- advanced_runtime_resource_pack@0.4.3
	- advancements-enlarger@0.2.4
	- advdebug@2.3.0
	- alaskanativecraft@1.3.1
	- ambientenvironment@6.0.21
	- amecsapi@1.1.4+mc21w16a
	- appleskin@mc1.17-2.1.2
	- aqupd@1.17-1.2.2
	- aqupdgrizzly@1.1.1
	- architectury@2.3.24
	- artifality@0.3.3
	- artifice@0.15.3+21w07a
	- attributefix@1.0.2
	- authme@1.5.0
	- autoconfig1u@3.3.1
	- balm-fabric@1.3.0+0
	- bannerpp@2.0.3+mc.1.17-rc1
	- basicaiots@1.3.1
	- bclib@0.2.4
	- beenfo@1.17.1-fabric0.36.1-1.3.2
	- betterend@0.10.5-pre
	- betterf3@1.1.5
	- bettermineshafts@1.17-1.0.1
	- betterstrongholds@1.17-1.1.1
	- biome_locator@1.1.3
	- blast@1.7
	- blockus@2.2.8+1.17.1
	- blue_endless_jankson@1.2.1
	- breakprogress@1.0.1
	- builtinservers@1.0.1-BETA+1.17
	- can-i-mine-this-block@1.1.0
	- cardinal-components-base@3.1.1
	- cardinal-components-entity@3.1.1
	- cardinal-components-world@3.0.0
	- carrier@1.8.0
	- charm@3.3.2
	- charmonium@3.3.0
	- cherishedworlds@2.0.1-1.17.1
	- cloth-api@2.0.54
	- cloth-armor-api-v1@1.5.47
	- cloth-basic-math@0.5.1
	- cloth-client-events-v0@2.0.54
	- cloth-common-events-v1@2.0.54
	- cloth-config2@5.0.38
	- cloth-datagen-api-v1@2.0.54
	- cloth-scissors-api-v1@2.0.54
	- cloth-utils-v1@2.0.54
	- clumps@fabric-1.17.1-7.0.4
	- coat@1.0.0-beta.9
	- com_electronwill_night-config_core@3.6.2
	- com_electronwill_night-config_toml@3.6.2
	- com_github_shevek_parallelgzip@af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
	- com_moandjiezana_toml_toml4j@0.7.2
	- conjuring@1.0.7
	- controlling@1.1.2
	- craftingtweaks@13.0.0+0
	- croptopia@1.6.1
	- crowdin-translate@1.3+1.17
	- crusade@1.2.4
	- dankstorage@2.1-1.17.1
	- dark-enchanting@0.4.1-1.17.1
	- dark-loading-screen@1.6.6
	- darkpaintings@4.0.2
	- dawn@2.0.5
	- de_javagl_obj@0.3.0
	- deathlog@0.1.3
	- defaultsettings@3.0.3
	- diggusmaximus@1.4.5-1.17
	- disable_custom_worlds_advice@1.3
	- dml-refabricated@0.4.4-beta
	- dml-refabricated-base@0.4.4-beta
	- dml-refabricated-events@0.4.4-beta
	- dml-refabricated-modular-armor@0.4.4-beta
	- dml-refabricated-rei@0.4.4-beta
	- dmlsimulacrum@1.0.2
	- dual_riders@1.0.5
	- dynamicfps@2.0.5
	- ecotones@0.8.1
	- eggtab@2.1.0+1.16-fabric
	- enchantmentdescriptions@4.0.1
	- entitybanners@1.0.1-BETA+1.17
	- expandedstorage@7.0.0
	- extragenerators@1.0.6-BETA+1.17
	- fabric@0.37.2+1.17
	- fabric-api-base@0.3.0+a02b44633d
	- fabric-api-lookup-api-v1@1.3.0+b246072f13
	- fabric-biome-api-v1@3.1.11+c345aea818
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c18
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.2.4+2e8bd82f18
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.1.0+a02b446318
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.3+kotlin.1.5.21
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+2e8bd82f18
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-permissions-api-v0@0.1-SNAPSHOT
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.0+a02b446318
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446318
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.7.0+2e8bd82f18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.1.4+a02b44633d
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabric-transfer-api-v1@1.1.0-pre.05+973bc52a18
	- fabricloader@0.11.6
	- fake-player-api@0.2.0
	- fallflyinglib@3.0.0-beta.2
	- fasttransferlib@0.5.6
	- ferritecore@3.0.1
	- fiber@0.23.0-2
	- flytre_lib@0.2.21
	- gateofbabylon@1.5.0-1.17
	- gbfabrictools@1.3.4+1.17
	- geckolib3@3.0.11
	- glassential@1.17-1.2.0
	- golemsgalore@1.0.2+mc.1.17
	- goml@1.4.0-beta
	- harvest_scythes@2.0.5
	- hologram-api@0.1.2+1.17.1
	- horseinfo@0.3.0-1.17
	- horsestatsvanilla@4.1.8
	- impaled@1.0.1
	- improved-stations@2.0.7
	- incantationem@1.1.2+1.17.1
	- indrev@1.10.0-alpha.12
	- inmis@2.3.1-1.17
	- inventorysorter@1.7.9-1.17
	- jankson@3.0.1+j1.2.0
	- java@16
	- jumpoverfences@1.16-0.0.3
	- kibe@1.8-BETA+1.17
	- kjsextras@1.3.2
	- ktdatataglib@1.5.4
	- kubejs@1605.3.10-build.9999
	- kyrptconfig@1.1.10-1.17
	- lakeside@1.1.0+1.17
	- lazydfu@0.1.2
	- libblockattributes_core@0.9.0
	- libblockattributes_fluids@0.9.0
	- libblockattributes_items@0.9.0
	- libcd@3.0.3+1.16.3
	- libgui@4.1.4+1.17.1
	- libninepatch@1.1.0
	- libzoomer@0.2.1+1.17
	- lifts@1.2-BETA+1.17
	- lightoverlay@6.0.0
	- lithium@0.7.3
	- lovely_snails@1.0.2+1.17
	- magna@1.5.5-1.17-pre4
	- maybe-data@1.0.1-1.17
	- me_hypherionmc_simple-rpc-lib@2.1.5
	- megane@5.2.0
	- megane-base@5.2.0
	- megane-extra-generators@5.2.0+1.0.5-BETA-1.17
	- megane-fabric-transfer@5.2.0+1.0.0-3fe3c3f518
	- megane-fast-transfer-lib@5.2.0+0.4.2
	- megane-industrial-revolution@5.2.0+1.10.0-alpha.4
	- megane-kibe@5.2.0+1.7.2-BETA-1.17
	- megane-lib-block-attributes@5.2.0+0.9.0
	- megane-modern-industrialization@5.2.0+0.5.6
	- megane-runtime@5.2.0
	- megane-team-reborn-energy@5.2.0+0.1.1
	- megane-tech-reborn@5.2.0+5.0.2-beta-build.38
	- megane-vanilla@5.2.0+1.17.1
	- megane-wireless-networks@5.2.0+1.1.1
	- minecraft@1.17.1
	- mm@2.2
	- mo_glass@1.5-MC1.17.1
	- mocolors@1.2.2
	- modern_industrialization@0.5.8
	- modmenu@2.0.2
	- morevillagers-fabric@2.0.4-SNAPSHOT
	- mostructures@1.3.0-pre1-1.17.1
	- mousewheelie@1.7.3-newconfig+mc1.17.1-pre1
	- myron@1.6.0
	- naturescompass@1.17.1-2.0.1-fabric
	- no-potion-offset@${version}
	- noanglebrackets@1.1.0
	- notes@1.0.6
	- nyfsquivers@Fabric-0.2.6
	- okzoomer@5.0.0-beta.2+1.17
	- omega-config@1.0.8
	- org_apache_commons_commons-compress@1.19
	- org_aperlambda_lambdajcommon@1.8.1
	- org_codehaus_groovy_groovy@3.0.8
	- org_codehaus_groovy_groovy-jsr223@3.0.8
	- org_jetbrains_kotlin_kotlin-reflect@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.21
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.21
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- org_tukaani_xz@1.8
	- outvoted@2.0.0-alpha.11
	- owo@0.1.1
	- packages@1.2.1
	- packet_tweaker@0.2.0-1.17-pre1
	- patchouli@1.17-54-FABRIC
	- placeholder-api@1.0.1+1.17
	- playerabilitylib@1.3.0
	- pling@1.4.0
	- polymer@0.1.0-pre9+1.17.1
	- promenade@2.1.2
	- quickshulker@1.2.2-1.17
	- ratsmischief@1.2
	- reach-entity-attributes@2.1.1
	- reborncore@5.0.5-beta+build.85
	- redbits@1.10.0
	- repurposed_structures@2.2.0+1.17.1
	- respawnablepets@1.17-3
	- rhino@1605.1.1-build.23
	- riverredux@0.2.0
	- roughlyenoughitems@6.0.264-alpha
	- rtree-3i-lite-fabric@0.3.0
	- runelic@3.0.1
	- secretrooms@1.0.0+1.17
	- server_translations_api@1.4.5+1.17
	- sgui@1.0.0-rc3-1.17.1
	- shulkerboxtooltip@3.0.1+1.17
	- shulkerutils@1.0.4-1.17
	- simple-rpc@1.17-2.3.1-fabric
	- slight-gui-modifications@2.0.1
	- slotlock@1.0.4-BETA+1.17
	- smootherbedrock@1.0.1
	- someforgepatchesported@1.0.1
	- spruceui@3.2.0+1.17
	- staffofbuilding@1.3.2-1.17
	- static-content@1.0.1-1.16.2
	- staticdata@1.1.2
	- step-height-entity-attribute@1.0.0
	- stoneholm@1.2.7
	- strawdummy@1.5.0
	- structurized@1.3.0
	- survivalisland@0.1.5
	- team_reborn_energy@0.1.1
	- techreborn@5.0.5-beta+build.85
	- terraform-biome-builder-api-v1@2.0.0
	- terraform-config-api-v1@2.0.0
	- terraform-overworld-biome-extensions-api-v1@2.0.0
	- terraform-shapes-api-v1@1.0.4
	- terraform-surfaces-api-v1@2.0.0
	- terraform-tree-api-v1@2.0.0
	- terraform-wood-api-v1@2.0.2
	- terrarianslimes@1.1-BETA+1.17
	- textile_backup@2.2.0-1.17
	- toolstats@2.0.1
	- tooltipfix@1.0.3-1.16
	- totemmod@0.3.2
	- traverse@4.0.0-beta.2
	- trident_return@1.2.4
	- trinkets@3.0.2
	- truerooms@1.1.5
	- tweed4_annotated@1.0.0
	- tweed4_base@1.0.0
	- tweed4_data@1.0.0
	- tweed4_data_hjson@1.0.0
	- tweed4_tailor_coat@1.0.0
	- tweed4_tailor_screen@1.0.0
	- universal-graves@1.0.7+1.17.1
	- untitledduckmod@0.3.0
	- urns@1.0.1
	- vanilla-hammers@3.1.2-1.17
	- vanillaexcavators@1.1.0
	- vanillaplusbiomes@0.3.2
	- villagershats@1.2.0
	- waystones@2.0.3
	- winged@1.17.1-3.0.0
	- wirelessnetworks@1.1.2
	- wolveswitharmor@1.6.0-1.17
	- woods_and_mires@1.1.0+1.17
	- workings@1.0.7
	- wthit@3.8.1
	- xaerominimap@21.14.1
	- xaeroworldmap@1.16.0
	- yosbr@0.1.1
	- yungsapi@1.17-Fabric-15
[12:43:26] [main/INFO]: Dependencies overridden for "fallflyinglib, couplings, crusade, kubejs, incantationem, trinkets, universal-graves, survivalisland, artifice, morevillagers-fabric, riverredux, indrev, fabric-dimensions-v1, kibe, megane, server_translations_api, addendum, ctm, diggusmaximus, yungsapi, maybe-data, packages, noanglebrackets, structurized, playerabilitylib, fabric-blockrenderlayer-v1, totemmod, terrarianslimes, mo_glass, libblockattributes_items, promenade, respawnablepets, fabric, dawn, dml-refabricated, flytre_lib, packet_tweaker, repurposed_structures, bitsandchisels, modmenu, eggtab, toolstats, shulkerutils, blockus, fabric-events-interaction-v0, mostructures, charmonium, enchantmentdescriptions, patchouli, mousewheelie, disable_custom_worlds_advice, mocolors, megane-runtime, betterstrongholds, expandedstorage, runelic, cardinal-components-entity, libblockattributes_fluids, architectury, cherishedworlds, authme, adorn, slotlock, cardinal-components-base, blast, golemsgalore, cpas, builtinservers, conjuring, charm, someforgepatchesported, aqupdgrizzly, fabric-item-groups-v0, bettermineshafts, geckolib3, darkpaintings, truerooms, fabric-renderer-api-v1, basicaiots, inventorysorter, notes, owo, placeholder-api, lithium, attributefix, harvest_scythes, redbits, waystones, clumps, myron, dual_riders, stoneholm, defaultsettings, wolveswitharmor, entitybanners, lazydfu, strawdummy, reach-entity-attributes, lovely_snails, fabric-renderer-registries-v1, deathlog, quickshulker, goml, artifality, libblockattributes_core, untitledduckmod, polymer, horsestatsvanilla, ktdatataglib, ratsmischief, woods_and_mires, jankson, static-content, fabric-renderer-indigo, wirelessnetworks, simple-rpc, dark-loading-screen, hologram-api, kyrptconfig, libgui, biome_locator, xaerominimap, fabric-rendering-v0, croptopia, omega-config, sgui, spruceui, gateofbabylon, winged, ambientenvironment, cardinal-components-world, fabric-biome-api-v1, advanced_runtime_resource_pack, lifts, ferritecore, textile_backup, lakeside, betterf3, extragenerators, carrier, horseinfo, fake-player-api, secretrooms"
[12:43:26] [main/WARN]: Mod `appleskin` (mc1.17-2.1.2) does not respect SemVer - comparison support is limited.
[12:43:26] [main/WARN]: Mod `nyfsquivers` (Fabric-0.2.6) does not respect SemVer - comparison support is limited.
[12:43:26] [main/WARN]: Mod `com_github_shevek_parallelgzip` (af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6) does not respect SemVer - comparison support is limited.
[12:43:26] [main/WARN]: Mod `clumps` (fabric-1.17.1-7.0.4) does not respect SemVer - comparison support is limited.
[12:43:26] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/D:/Servers/Minecraft/Modded/All%20of%20Fabric%204/AllofFabric4Server-0.0.9/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[12:43:26] [main/INFO]: Compatibility level set to JAVA_16
[12:43:27] [main/WARN]: Reference map 'addendum-refmap.json' for addendum.mixins.json could not be read. If this is a development environment you can ignore this message
[12:43:27] [main/WARN]: Reference map 'static-content-refmap.json' for static-content.mixins.json could not be read. If this is a development environment you can ignore this message
[12:43:27] [main/WARN]: Reference map 'owo-refmap.json' for owo.mixins.json could not be read. If this is a development environment you can ignore this message
[12:43:27] [main/INFO]: Loaded configuration file for Lithium: 80 options available, 0 override(s) found
[12:43:27] [main/WARN]: Reference map 'dmlSimulacrum-refmap.json' for dmlSimulacrum.mixins.json could not be read. If this is a development environment you can ignore this message
[12:43:27] [main/WARN]: Reference map 'grizzlybear-refmap.json' for grizzlybear.mixins.json could not be read. If this is a development environment you can ignore this message
[12:43:27] [main/WARN]: Reference map 'craftingtweaks-fabric-refmap.json' for craftingtweaks.mixins.json could not be read. If this is a development environment you can ignore this message
[12:43:27] [main/WARN]: Reference map 'caracalmob-refmap.json' for caracalmob.mixins.json could not be read. If this is a development environment you can ignore this message
[12:43:27] [main/INFO]: [MixinConfig] Not adding collection_enchantment.TryBreakBlockMixin
[12:43:27] [main/INFO]: [MixinConfig] Not adding snow_storms.PreventSnowMeltingMixin
[12:43:27] [main/INFO]: [MixinConfig] Not adding helper.CheckEnchantingPowerMixin
[12:43:27] [main/INFO]: [MixinConfig] Not adding devenv.FixDevAuthSpamMixin
[12:43:27] [main/INFO]: [MixinConfig] Not adding collection_enchantment.AddDroppedItemToInventoryMixin
[12:43:27] [main/INFO]: [MixinConfig] Not adding helper.ShowEnchantmentParticlesMixin
[12:43:27] [main/INFO]: [MixinConfig] Not adding snow_storms.RenderHeavySnowTextureMixin
[12:43:27] [main/INFO]: [MixinConfig] Not adding snow_storms.SetEntityFreezingMixin
[12:43:27] [main/INFO]: [MixinConfig] Not adding snow_storms.PlaceMoreSnowMixin

**Comment by AbyssalCode** [comment]
Running java 16 now, server keeps crashing on launch.
-v 0.0.9  server files and launcher
