### ISSUE TITLE
Crash on Start "java @ [>=16]"

### ISSUE THREAD

**Issue by stephen-smith** [TeamAOF/All-of-Fabric-4#86]
Summary:

```
[17:08:16] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: mo_glass requires {java @ [>=16]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
```

Full log attached. 
[latest.log](https://github.com/TeamAOF/All-of-Fabric-4/files/7110583/latest.log)

I'm using the MultiMC5 launcher (I'm on Linux so I can't use the Curseforge launcher), and it complains that fabric-0.11.6 is an "Unknown mod loader" while it imports the zip file, but I did "add" Fabric 0.11.6 to the instance "Version"

**Comment by stephen-smith** [comment]
Oh, and I tried both with Java 8, which I use for most modpacks, and Java 14, which it my default Java.  Same error.

**Comment by stephen-smith** [comment]
D'Oh upgrading to Java 16 got me to at least the main menu.

I've been using Java so long, I thought the java >= 16 was trying to make sure Java 6 (aka 1.6) was present.
